# Test an unscented Kalman Filter for processing
following method described by [Roger Labbe](https://filterpy.readthedocs.io/en/latest/kalman/UnscentedKalmanFilter.html)

Need to install filterpy
```
pip install filterpy
```

In [1]:
# test case using randomly generated 'data' that bounces about unity.publish_display_data
# example is here along with usage of the UKF 
# https://filterpy.readthedocs.io/en/latest/kalman/UnscentedKalmanFilter.html
from filterpy.kalman import MerweScaledSigmaPoints, UnscentedKalmanFilter 
from filterpy.common import Q_discrete_white_noise
import numpy as np

In [2]:
# example from instructions
from numpy.random import randn

def fx(x, dt):
    # state transition function - predict next state based
    # on constant velocity model x = vt + x_0
    F = np.array([[1, dt, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, dt],
                  [0, 0, 0, 1]], dtype=float)
    return np.dot(F, x)

def hx(x):
   # measurement function - convert state into a measurement
   # where measurements are [x_pos, y_pos]
   return np.array([x[0], x[2]])


dt = 0.1
# create sigma points to use in the filter. This is standard for Gaussian processes
points = MerweScaledSigmaPoints(4, alpha=.1, beta=2., kappa=-1)

kf = UnscentedKalmanFilter(dim_x=4, dim_z=2, dt=dt, fx=fx, hx=hx, points=points)
kf.x = np.array([-1., 1., -1., 1]) # initial state
kf.P *= 0.2 # initial uncertainty
z_std = 0.1
kf.R = np.diag([z_std**2, z_std**2]) # 1 standard
kf.Q = Q_discrete_white_noise(dim=2, dt=dt, var=0.01**2, block_size=2)

zs = [[i+randn()*z_std, i+randn()*z_std] for i in range(50)] # measurements


In [3]:
kf

UnscentedKalmanFilter object
x = [-1.  1. -1.  1.]
P = [[0.2 0.  0.  0. ]
     [0.  0.2 0.  0. ]
     [0.  0.  0.2 0. ]
     [0.  0.  0.  0.2]]
x_prior = [0. 0. 0. 0.]
P_prior = [[1. 0. 0. 0.]
           [0. 1. 0. 0.]
           [0. 0. 1. 0.]
           [0. 0. 0. 1.]]
Q = [[2.5e-09 5.0e-08 0.0e+00 0.0e+00]
     [5.0e-08 1.0e-06 0.0e+00 0.0e+00]
     [0.0e+00 0.0e+00 2.5e-09 5.0e-08]
     [0.0e+00 0.0e+00 5.0e-08 1.0e-06]]
R = [[0.01 0.  ]
     [0.   0.01]]
S = [[0. 0.]
     [0. 0.]]
K = [[0. 0.]
     [0. 0.]
     [0. 0.]
     [0. 0.]]
y = [0. 0.]
log-likelihood = -708.3964185322641
likelihood = 2.2250738585072014e-308
mahalanobis = 0.0
sigmas_f = [[0. 0. 0. 0.]
            [0. 0. 0. 0.]
            [0. 0. 0. 0.]
            [0. 0. 0. 0.]
            [0. 0. 0. 0.]
            [0. 0. 0. 0.]
            [0. 0. 0. 0.]
            [0. 0. 0. 0.]
            [0. 0. 0. 0.]]
h = [[0. 0.]
     [0. 0.]
     [0. 0.]
     [0. 0.]
     [0. 0.]
     [0. 0.]
     [0. 0.]
     [0. 0.]
     [0. 0.]]
Wm 

In [ ]:
for z in zs:
    kf.predict()
    kf.update(z)
    print(kf.x, 'log-likelihood', kf.log_likelihood)

In [3]:
kf

UnscentedKalmanFilter object
x = [49.0230989  10.00526093 48.98863223  9.99709161]
P = [[7.86041002e-04 2.46861420e-04 2.85153685e-25 1.34503106e-26]
     [2.46861420e-04 1.13702678e-04 4.68531545e-26 2.38611046e-27]
     [2.85159554e-25 4.68511617e-26 7.86041002e-04 2.46861420e-04]
     [1.34517200e-26 2.38595884e-27 2.46861420e-04 1.13702678e-04]]
x_prior = [49.02349745 10.00538607 48.98599907  9.99626481]
P_prior = [[8.53097558e-04 2.67916780e-04 2.21975522e-25 2.95822839e-31]
           [2.67916780e-04 1.20313936e-04 3.28669293e-26 1.72563323e-31]
           [2.21981430e-25 3.28649487e-26 8.53097558e-04 2.67916780e-04]
           [1.71720028e-30 2.47349353e-32 2.67916780e-04 1.20313936e-04]]
Q = [[2.5e-09 5.0e-08 0.0e+00 0.0e+00]
     [5.0e-08 1.0e-06 0.0e+00 0.0e+00]
     [0.0e+00 0.0e+00 2.5e-09 5.0e-08]
     [0.0e+00 0.0e+00 5.0e-08 1.0e-06]]
R = [[0.01 0.  ]
     [0.   0.01]]
S = [[1.08530951e-02 6.77765533e-25]
     [6.77771742e-25 1.08530951e-02]]
K = [[ 7.86038502e-02 -5.021

In [6]:
print(kf.x)
print(hx(kf.x))

[48.98047708  9.99454616 49.01515539  9.99751617]
[48.98047708 49.01515539]


In [4]:
points

MerweScaledSigmaPoints object
n = 4
alpha = 0.1
beta = 2.0
kappa = -1
Wm = [-132.33333333   16.66666667   16.66666667   16.66666667   16.66666667
        16.66666667   16.66666667   16.66666667   16.66666667]
Wc = [-129.34333333   16.66666667   16.66666667   16.66666667   16.66666667
        16.66666667   16.66666667   16.66666667   16.66666667]
subtract = <ufunc 'subtract'>
sqrt = <function cholesky at 0x10e04a700>